export const rectConfig = {
    rotation: 0,
    scaleX: 1,
    scaleY: 1,
    type: 'Rect',
    x: 250,
    y: 250,
    id: '',
    width: 100,
    height: 100,
    fill: 'rgb(179 177 177)',
    draggable: true,
    name: 'object',
};

export const circleConfig = {
    rotation: 0,
    scaleX: 1,
    scaleY: 1,
    type: 'Circle',
    x: 250,
    y: 250,
    width: 100,
    height: 100,
    id: '',
    fill: 'rgb(179 177 177)',
    draggable: true,
    name: 'object',
};

export const triangleConfig = {
    rotation: 0,
    scaleX: 1,
    scaleY: 1,
    type: 'RegularPolygon',
    x: 250,
    y: 250,
    width: 100,
    height: 100,
    id: '',
    sides: 3,
    fill: 'rgb(179 177 177)',
    draggable: true,
    name: 'object',
};

export const hexagonConfig = {
    rotation: 0,
    scaleX: 1,
    scaleY: 1,
    type: 'RegularPolygon',
    x: 250,
    y: 250,
    width: 100,
    id: '',
    sides: 6,
    radius: 50,
    fill: 'rgb(179 177 177)',
    draggable: true,
    name: 'object',
};

export const octagonConfig = {
    rotation: 0,
    scaleX: 1,
    scaleY: 1,
    type: 'RegularPolygon',
    x: 250,
    y: 250,
    id: '',
    sides: 8,
    radius: 50,
    fill: 'rgb(179 177 177)',
    draggable: true,
    name: 'object',
};
